### ISSUE TITLE
Health insurance info

### ISSUE THREAD

**Issue by mhyee** [khoury-gsa/khoury-gsa.github.io#10]
People commonly ask about health insurance, dental insurance, vision, etc. We should have a link to the [NUSHP page](https://studenthealthplan.northeastern.edu/).

Maybe an FAQs would be useful... but we already have too many pages (official student handbook, Confluence, FAQs Google Doc, KGSA website wiki). Maybe we should start consolidating some of the student-maintained stuff (and maybe that should be a separate issue)...

**Comment by julbinb** [comment]
I agree that adding the link would be good.

For the KGSA website wiki, we decided to move info to confluence if I remember correctly. There was already s short page with eyeglasses shops. I guess adding some info on dental would make sense.

There was also a suggestion to link especially useful confluence pages from the KGSA website...

**Comment by ulysses4ever** [comment]
I added the link in khoury-gsa/khoury-gsa.github.io@eea2f45. As for the FAQ, a better fit for FAQs would be some kind of wiki. So, close this for now. Feel free to reopen if you think we could put some more on the website. Somediscussion is on khoury-gsa/private#127.
