### ISSUE TITLE
Upload startup funds / depreciation policy document

### ISSUE THREAD

**Issue by mhyee** [khoury-gsa/khoury-gsa.github.io#13]

**Comment by ulysses4ever** [comment]
Thanks for tracking it down! Done!

**Comment by mhyee** [comment]
Of course, the document got revised after we uploaded it. 🥲 

Might also be useful to include this table.

![image](https://user-images.githubusercontent.com/547059/187754924-280283e2-1afe-4ba3-9fa5-32a94424206d.png)

[PhD_Startup Spring 2022 RVSD 08.2022.pdf](https://github.com/khoury-gsa/khoury-gsa.github.io/files/9464068/PhD_Startup.Spring.2022.RVSD.08.2022.pdf)

**Comment by julbinb** [comment]
Decided to replace the pdf with a link to the corresponding SharePoint. @ulysses4ever agreed to update the website

**Comment by ulysses4ever** [comment]
A stab at that: #18

**Comment by ulysses4ever** [comment]
Merged the above
