### ISSUE TITLE
Update index page

### ISSUE THREAD

**Issue by mhyee** [khoury-gsa/khoury-gsa.github.io#15]
![image](https://user-images.githubusercontent.com/547059/187755983-0fcb978a-281c-413e-bd97-ea14079051aa.png)

And once we get the SharePoint link, we should add it.

**Comment by mhyee** [comment]
I don't think there's anything interesting on the main SharePoint page, most of the content is for master's students.

So we should link directly to the PhD section: https://northeastern.sharepoint.com/sites/KhouryResourceCenter/SitePages/PHD.aspx?csf=1&web=1&e=Vbcor3

**Comment by ulysses4ever** [comment]
The link to SP is there. The table is being added in #19.

**Comment by ulysses4ever** [comment]
Merged the above
