### ISSUE TITLE
Add link to Khoury SharePoint resource center

### ISSUE THREAD

**Issue by julbinb** [khoury-gsa/khoury-gsa.github.io#17]
Add new links:

- https://northeastern.sharepoint.com/sites/KhouryResourceCenter
- https://northeastern.sharepoint.com/sites/KhouryResourceCenter/SitePages/PHD.aspx

**Comment by ulysses4ever** [comment]
@mhyee suggests (in #15) to only put the second link, and I tend to agree. That's what #16 does.

**Comment by julbinb** [comment]
Agreed
